Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - musicz.gemspec
    - 'spec/**/*'
