# frozen_string_literal: true

require "musicz/entities/alias"
require "musicz/entities/area"
require "musicz/entities/artist_credit"
require "musicz/entities/artist_list"
require "musicz/entities/artist_reference"
require "musicz/entities/artist"
require "musicz/entities/disc_id"
require "musicz/entities/error"
require "musicz/entities/life_span"
require "musicz/entities/media"
require "musicz/entities/rating"
require "musicz/entities/recording_reference"
require "musicz/entities/recording"
require "musicz/entities/release_event"
require "musicz/entities/release_reference"
require "musicz/entities/release"
require "musicz/entities/tag"
require "musicz/entities/text_representation"
require "musicz/entities/track"
